name: test move action
on: workflow_dispatch

jobs:
  release: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: alvarolorentedev/notion-cms@main
        with:
          notion-api-key: ${{ secrets.NOTION_API_KEY }}
          notion-database-id: ${{ secrets.NOTION_DATABASE_ID }}
      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: '[skip ci] Moved scheduled articles'
